name: El Peñol
favicon: null
layout_spectrum: 0.9808250507339835
typography_spectrum: 0.703413242707029
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.4954336395021528
  lightness: 0.04897361039184034
  saturation: 0.8838879407849163
  rhythmicContrast: 0.16413342580199242
purpose: []
